//HttpResponse res1 = RestCallOutsInnovas.getAnimals();
//HttpResponse res2 = RestCallOutsInnovas.getBlogs();
//HttpResponse res3 = restPostCallOut.postAnimal();
//HttpResponse res4 = RestCallOutsInnovas.getProducts();

// access token = 903f4737f34e2394bd93c99b5fa2905071676f38d7f82ee6438c9f38b714c8eb

//https://gorest.co.in//public/v2/users



//HttpResponse res5 = restPostCallOut.postGoRestObj();
HttpResponse res6 = RestCallOutsInnovas.getContactUsers();

